drop table if exists {{ params.schema_name }}.{{ params.table_name }};
create table if not exists {{ params.schema_name }}.{{ params.table_name }} like {{ params.schema_name }}.zendesk_users;
copy into {{ params.schema_name }}.{{ params.table_name }} from 's3://airflow-success/zendesk_extract/users/{{ds}}/users.csv'
credentials = (aws_key_id='{{ conn.my_conn_s3.extra_dejson.aws_access_key_id }}' aws_secret_key='{{ conn.my_conn_s3.extra_dejson.aws_secret_access_key }}')
file_format = (type = csv, record_delimiter= '\n' field_delimiter=',' field_optionally_enclosed_by='"' skip_header=1)
;

merge into {{ params.schema_name }}.zendesk_users using {{ params.schema_name }}.{{ params.table_name }}
  on zendesk_users.id = {{ params.table_name }}.id
  when matched then update set
    zendesk_users.id = {{ params.table_name }}.id,
    zendesk_users.url = {{ params.table_name }}.url,
    zendesk_users.name = {{ params.table_name }}.name,
    zendesk_users.email = {{ params.table_name }}.email,
    zendesk_users.created_at = {{ params.table_name }}.created_at,
    zendesk_users.updated_at = {{ params.table_name }}.updated_at,
    zendesk_users.time_zone = {{ params.table_name }}.time_zone,
    zendesk_users.iana_time_zone = {{ params.table_name }}.iana_time_zone,
    zendesk_users.phone = {{ params.table_name }}.phone,
    zendesk_users.shared_phone_number = {{ params.table_name }}.shared_phone_number,
    zendesk_users.locale_id = {{ params.table_name }}.locale_id,
    zendesk_users.locale = {{ params.table_name }}.locale,
    zendesk_users.organization_id = {{ params.table_name }}.organization_id,
    zendesk_users.role = {{ params.table_name }}.role,
    zendesk_users.verified = {{ params.table_name }}.verified,
    zendesk_users.external_id = {{ params.table_name }}.external_id,
    zendesk_users.tags = {{ params.table_name }}.tags,
    zendesk_users.alias = {{ params.table_name }}.alias,
    zendesk_users.active = {{ params.table_name }}.active,
    zendesk_users.shared = {{ params.table_name }}.shared,
    zendesk_users.shared_agent = {{ params.table_name }}.shared_agent,
    zendesk_users.last_login_at = {{ params.table_name }}.last_login_at,
    zendesk_users.two_factor_auth_enabled = {{ params.table_name }}.two_factor_auth_enabled,
    zendesk_users.signature = {{ params.table_name }}.signature,
    zendesk_users.details = {{ params.table_name }}.details,
    zendesk_users.notes = {{ params.table_name }}.notes,
    zendesk_users.role_type = {{ params.table_name }}.role_type,
    zendesk_users.custom_role_id = {{ params.table_name }}.custom_role_id,
    zendesk_users.moderator = {{ params.table_name }}.moderator,
    zendesk_users.ticket_restriction = {{ params.table_name }}.ticket_restriction,
    zendesk_users.only_private_comments = {{ params.table_name }}.only_private_comments,
    zendesk_users.restricted_agent = {{ params.table_name }}.restricted_agent,
    zendesk_users.suspended = {{ params.table_name }}.suspended,
    zendesk_users.default_group_id = {{ params.table_name }}.default_group_id,
    zendesk_users.report_csv = {{ params.table_name }}.report_csv,
    zendesk_users."photo.url" = {{ params.table_name }}."photo.url",
    zendesk_users."photo.id" = {{ params.table_name }}."photo.id",
    zendesk_users."photo.file_name" = {{ params.table_name }}."photo.file_name",
    zendesk_users."photo.content_url" = {{ params.table_name }}."photo.content_url",
    zendesk_users."photo.mapped_content_url" = {{ params.table_name }}."photo.mapped_content_url",
    zendesk_users."photo.content_type" = {{ params.table_name }}."photo.content_type",
    zendesk_users."photo.size" = {{ params.table_name }}."photo.size",
    zendesk_users."photo.width" = {{ params.table_name }}."photo.width",
    zendesk_users."photo.height" = {{ params.table_name }}."photo.height",
    zendesk_users."photo.inline" = {{ params.table_name }}."photo.inline",
    zendesk_users."photo.deleted" = {{ params.table_name }}."photo.deleted",
    zendesk_users."photo.thumbnails" = {{ params.table_name }}."photo.thumbnails",
    zendesk_users."user_fields.agent_ooo" = {{ params.table_name }}."user_fields.agent_ooo",
    zendesk_users.photo = {{ params.table_name }}.photo,
    zendesk_users.permanently_deleted = {{ params.table_name }}.permanently_deleted
  when not matched then insert (
    id,
    url,
    name,
    email,
    created_at,
    updated_at,
    time_zone,
    iana_time_zone,
    phone,
    shared_phone_number,
    locale_id,
    locale,
    organization_id,
    role,
    verified,
    external_id,
    tags,
    alias,
    active,
    shared,
    shared_agent,
    last_login_at,
    two_factor_auth_enabled,
    signature,
    details,
    notes,
    role_type,
    custom_role_id,
    moderator,
    ticket_restriction,
    only_private_comments,
    restricted_agent,
    suspended,
    default_group_id,
    report_csv,
    "photo.url",
    "photo.id",
    "photo.file_name",
    "photo.content_url",
    "photo.mapped_content_url",
    "photo.content_type",
    "photo.size",
    "photo.width",
    "photo.height",
    "photo.inline",
    "photo.deleted",
    "photo.thumbnails",
    "user_fields.agent_ooo",
    photo,
    permanently_deleted
  ) values (
    {{ params.table_name }}.id,
    {{ params.table_name }}.url,
    {{ params.table_name }}.name,
    {{ params.table_name }}.email,
    {{ params.table_name }}.created_at,
    {{ params.table_name }}.updated_at,
    {{ params.table_name }}.time_zone,
    {{ params.table_name }}.iana_time_zone,
    {{ params.table_name }}.phone,
    {{ params.table_name }}.shared_phone_number,
    {{ params.table_name }}.locale_id,
    {{ params.table_name }}.locale,
    {{ params.table_name }}.organization_id,
    {{ params.table_name }}.role,
    {{ params.table_name }}.verified,
    {{ params.table_name }}.external_id,
    {{ params.table_name }}.tags,
    {{ params.table_name }}.alias,
    {{ params.table_name }}.active,
    {{ params.table_name }}.shared,
    {{ params.table_name }}.shared_agent,
    {{ params.table_name }}.last_login_at,
    {{ params.table_name }}.two_factor_auth_enabled,
    {{ params.table_name }}.signature,
    {{ params.table_name }}.details,
    {{ params.table_name }}.notes,
    {{ params.table_name }}.role_type,
    {{ params.table_name }}.custom_role_id,
    {{ params.table_name }}.moderator,
    {{ params.table_name }}.ticket_restriction,
    {{ params.table_name }}.only_private_comments,
    {{ params.table_name }}.restricted_agent,
    {{ params.table_name }}.suspended,
    {{ params.table_name }}.default_group_id,
    {{ params.table_name }}.report_csv,
    {{ params.table_name }}."photo.url",
    {{ params.table_name }}."photo.id",
    {{ params.table_name }}."photo.file_name",
    {{ params.table_name }}."photo.content_url",
    {{ params.table_name }}."photo.mapped_content_url",
    {{ params.table_name }}."photo.content_type",
    {{ params.table_name }}."photo.size",
    {{ params.table_name }}."photo.width",
    {{ params.table_name }}."photo.height",
    {{ params.table_name }}."photo.inline",
    {{ params.table_name }}."photo.deleted",
    {{ params.table_name }}."photo.thumbnails",
    {{ params.table_name }}."user_fields.agent_ooo",
    {{ params.table_name }}.photo,
    {{ params.table_name }}.permanently_deleted
  )
;
